### ISSUE TITLE
Setup auto publishing

### ISSUE THREAD

**Issue by yoavweiss** [w3c/requestidlecallback#100]
Current spec is out of date. We should setup autopublishing.

/cc @caribouW3 @nicjansma

**Comment by clelland** [comment]
@plehegar, is this something that you can help with?

**Comment by plehegar** [comment]
Let me see if @caribouW3 can do it this week, otherwise I'll get to it.

**Comment by caribouW3** [comment]
The latest publication in 2017 was a Proposed Recommendation. There were non-editorial changes so it has to go back to WD. We can publish a WD then start a wide review if it's ready to request CR.

**Comment by yoavweiss** [comment]
Sounds good, thanks! :)

**Comment by caribouW3** [comment]
@yoavweiss  auto-publish script is now ready, but going back to WD can't be auto-published yet, so I'll prepare a manual publication for later this week.

**Comment by plehegar** [comment]
Can't this be closed now?
