### ISSUE TITLE
Do we need to clarify that microtasks will execute within this period?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/requestidlecallback#13]
This is a bit vague but is something I as thinkin on this morning. It seems that downstream microtasks from code within a requeestIdleCallback could cause the code to have effects past its deadline. Is any processing model update necessary to improve that OR is that just something we should expect web page developers to understand?

(My initial thinking is that web page developers will just need to keep that in mind. The purpose of this issue is to ensure others agreed.)

**Comment by igrigorik** [comment]
Hmm, I think this is a "developers will have to keep this in mind". There isn't anything we can do about this in rIC's processing model.. since the callback can do arbitrary work.

That said, perhaps it does make sense to add a note reminding developers to be careful about what and how they schedule within rIC's callback?

**Comment by rmcilroy** [comment]
I agree with @igrigorik, I don't think we can specify anything about this in the processing model, but happy to take suggestions on adding a note to remind developers about this in the spec.

**Comment by igrigorik** [comment]
@rmcilroy it may be good to add a brief note [below Fig 1](https://w3c.github.io/requestidlecallback/#figure1) indicating that some operations invoked within the rIC callback may schedule other (microtask) work that would run after the idle callback has finished.. If that's the case, the application should account for that by yielding before the deadline expires to avoid blowing the frame budget. (Except, worded more nicely.. :))

**Comment by toddreifsteck** [comment]
This sounds useful to me. Thanks!

**Comment by rmcilroy** [comment]
Attempted to clarify this in #15. PTAL, thanks.
