### ISSUE TITLE
should requestIdleCallback return unsigned long?

### ISSUE THREAD

**Issue by tetsuharuohzeki** [w3c/requestidlecallback#17]
revision: 7a1bbbb6f4ebc2f891cd74023b28add9e2dd7c33

By this spec revision,  [_idle callback identifier_](https://w3c.github.io/requestidlecallback/#dfn-idle-callback-identifier) is only incremented and not be decremented at all, thus this value will not be a negative value. So I feel [unsigned long in WebIDL](http://heycam.github.io/webidl/#idl-unsigned-long)  is more suitable type for the return value of `requestIdleCallback()`.

**Comment by igrigorik** [comment]
Seems reasonable. That said, with my 'spec hat' on I'd prefer that we stay consistent with requestAnimationFrame: https://html.spec.whatwg.org/#window. Would you be willing to start a conversation [on whatwg](https://github.com/whatwg/html) first to see if that can be updated?

**Comment by tetsuharuohzeki** [comment]
Hmm, okay, I'll file a new proposal issue which is about `requestAnimationFrame` to whatwg/html.

**Comment by tetsuharuohzeki** [comment]
By https://github.com/whatwg/html/pull/97, `requestAnimationFrame()` returns unsigned long now in whatwg/html.

**Comment by igrigorik** [comment]
Awesome, thanks for the quick turnaround! @rmcilroy any objections?

**Comment by rmcilroy** [comment]
No objections :+1:
