### ISSUE TITLE
Improve IDL markup

### ISSUE THREAD

**Issue by igrigorik** [w3c/requestidlecallback#24]
Editorial nitpick: https://github.com/w3c/requestidlecallback/blob/gh-pages/index.html#L229-L245

Respec is throwing an error (top right corner of the spec). It'd be great to convert above markup into respec compatible format to get code highlighting and resolve the error.

https://www.w3.org/respec/guide.html#webidl-support - see examples doc at the bottom. Also, example from FT spec: https://github.com/w3c/frame-timing/blob/gh-pages/index.html#L115-L137

**Comment by rmcilroy** [comment]
Hopefully done in #30. I've never used the respec webidl markup before though, so comments on that pull request are welcome.
