### ISSUE TITLE
Are we sure we want integer handles?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/requestidlecallback#26]
The use of unsigned long handles is problematic.  I thought we had this conversation with `requestAnimationFrame` too, and am not sure why it went with them after all, but there are two main problems: (a) You have to deal with overflow of the counter (which specs tend to not do, somehow) and (b) You can cancel other people's requests (or indeed all of them).

Vending some sort of guaranteed-unforgeable handles might be a better approach.  Or we could keep the integer handles for consistency with all the other broken timing callback APIs we have in the platform, I guess...

**Comment by rmcilroy** [comment]
The use of integer handles here was modivated by consistency with the other timing callback APIs. Personally I agree that vending unforgeable handles might be a better approach, but I also think consistency with the other timing APIs is important.

**Comment by igrigorik** [comment]
> The use of integer handles here was modivated by consistency with the other timing callback APIs. Personally I agree that vending unforgeable handles might be a better approach, but I also think consistency with the other timing APIs is important.

Ditto.

**Comment by igrigorik** [comment]
Closing. Please feel free to reopen if this needs further action.
