### ISSUE TITLE
implementations should be allowed to consider work beyond "other event loops"

### ISSUE THREAD

**Issue by dbaron** [w3c/requestidlecallback#46]
This is filed as a followup from https://github.com/w3ctag/spec-reviews/issues/70 .

[5.1 Start an event loop's idle period](https://w3c.github.io/requestidlecallback/#start-an-event-loop-s-idle-period) currently says "and that background work could be executed on this event loop without impacting any high priority work occurring on other event-loops".

This seems like it precludes user agents from considering what's happening in a worker thread, or what's happening in other processes on the system that it's aware of.  While I don't think considering such things should be required, it seems like they should be allowed, perhaps just by adding "or elsewhere" after "on other event-loops".

(Also, it should be "event loops" rather than "event-loops".)

**Comment by igrigorik** [comment]
Yep, seems reasonable. @toddreifsteck @plehegar any objections?

**Comment by rmcilroy** [comment]
Yup, sounds good to me.

**Comment by plehegar** [comment]
:+1:
