### ISSUE TITLE
Transition Level 1 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/requestidlecallback#48]
- **Known / outstanding spec issues**
  - [ ] Address editorial feedback: https://github.com/w3c/requestidlecallback/milestone/1
- **Web platform tests**
  - [x] Land https://github.com/w3c/web-platform-tests/pull/2163. 
- **Privacy and security**
  - [x] https://w3c.github.io/requestidlecallback/#privacy-and-security
- **Implementations**
  - [x] Chrome: [M47+](https://www.chromestatus.com/feature/5572795866021888)
  - [x] Firefox: [M52](https://bugzilla.mozilla.org/show_bug.cgi?id=1198381)
  - [ ] Edge: [under consideration](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/requestidlecallback/)
  - [ ] Safari: no public signals
- **Public signals: adoption, feedback...**
  - https://developers.google.com/web/updates/2015/08/using-requestidlecallback

**Comment by igrigorik** [comment]
For posterity: approved CR transition [on last week's WG call](https://lists.w3.org/Archives/Public/public-web-perf/2016Dec/0011.html), modulo resolving https://github.com/w3c/requestidlecallback/issues/44.

**Comment by rmcilroy** [comment]
Great stuff, thanks for pushing this forward to CR Ilya.

**Comment by igrigorik** [comment]
@plehegar @siusin I believe the doc should be ready for CR. Would one of you be willing to file the transition request?

**Comment by plehegar** [comment]
https://www.w3.org/TR/2017/CR-requestidlecallback-20170131/

**Comment by igrigorik** [comment]
\o/ ... thanks Philippe!

**Comment by rmcilroy** [comment]
Awesome! Thanks Philippe
