### ISSUE TITLE
Images not found for w3.org

### ISSUE THREAD

**Issue by Krinkle** [w3c/requestidlecallback#51]
While the images are fine on <https://w3c.github.io/requestidlecallback/>, on <https://www.w3.org/TR/requestidlecallback/> most of the images are broken due to the url yielding a 404 Not Found response.

For example, <https://www.w3.org/TR/requestidlecallback/#idle-periods> got a 404 Not Found for <https://www.w3.org/TR/requestidlecallback/images/image01.png>.

**Comment by siusin** [comment]
Thanks! It should be working now.
