### ISSUE TITLE
timeRemaining() is badly defined, deadline argument

### ISSUE THREAD

**Issue by annevk** [w3c/requestidlecallback#55]
The deadline argument isn't passed to IdleDeadLine...

**Comment by plehegar** [comment]
[This one requires some tightening of the algorithms]

**Comment by swickr** [comment]
I suspect the text "the deadline argument passed to IdleDeadline" should be something like "the _deadline_ in the IdleDeadLine object"

(ref [5.2 Invoke idle callbacks algorithm](https://w3c.github.io/requestidlecallback/#invoke-idle-callbacks-algorithm))

**Comment by swickr** [comment]
dummy

**Comment by annevk** [comment]
Yeah, usually you have something that says "IdleDeadLine objects have an associated X." And then elsewhere you have "Return _idleDeadLineInstance_'s X."

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/requestidlecallback/pull/58, closing.
