### ISSUE TITLE
`isExceeded` specified backward?

### ISSUE THREAD

**Issue by lawnsea** [w3c/requestidlecallback#6]
The spec says the following on [L299-300](https://github.com/w3c/requestidlecallback/blob/gh-pages/index.html#L299-L300):

> When the <code>isExceeded()</code> method on an <code>IdleDeadline</code> object is invoked, it MUST return <code>true</code> if the
>  <code>deadline</code> attribute is greater than or equal to the time as returned by <code><a href="http://www.w3.org/TR/hr-time-2/#widl-Performance-now-DOMHighResTimeStamp">performance.now()</a></code>  [[!hr-time-2]], and <code>false</code> otherwise.

If the value of the `deadline` timestamp is greater than that returned from `performance.now()`, doesn't that mean the deadline is in the future and thus has not been exceeded?

**Comment by rmcilroy** [comment]
Yes you are right - I seem to have a blind spot for getting comparisons in the correct order... 

I created a pull request at https://github.com/w3c/requestidlecallback/pull/9 to fix this. @plehegar, look good to you?
