### ISSUE TITLE
(Editorial) Example 1 does not render properly

### ISSUE THREAD

**Issue by iherman** [w3c/requestidlecallback#67]
The original source says

```
var x = Math.random() * r * 2 - r;
var y = Math.random() * r * 2 - r;
```
However, the '*' character does not display on some (all?) browsers; an empty space is displayed. See, for example, 

![image](https://user-images.githubusercontent.com/520723/31379982-3e18d4ba-adb0-11e7-889b-a1787990eee6.png)

I see the same in FF, Vivaldi, FF Dev edition, Chrome...

**Comment by igrigorik** [comment]
Thanks for flagging this. Paging @marcoscaceres.. This looks like a respec issue, I think.

**Comment by marcoscaceres** [comment]
Whoa.. yeah. That's messed up. The highlighter seems to be stripping the "*". Will poke at it a bit more.  You might want to add CSS class "nohighlight" for now.

**Comment by marcoscaceres** [comment]
Filed: https://github.com/w3c/respec/issues/1389

Will poke at it look soon.

**Comment by marcoscaceres** [comment]
It's actually a bug with the markdown parser :( I might need to replace the markdown parser. Looking for options.

**Comment by marcoscaceres** [comment]
@igrigorik, unfortunately, it's going to be another 2 weeks or so before I get to this. Could you maybe change the example to (the problem happens when "*" appears twice on the same line):

```JS
var rand = Math.random() * r;
var x =  rand * 2 - r;
rand = Math.random() * r;
var y =  rand * 2 - r;
```

**Comment by igrigorik** [comment]
Closing, resolved via https://github.com/rmcilroy/requestidlecallback/commit/c216c4b1190f79fb4cefd32eedfec590fe997774. Thanks Ross!

**Comment by rmcilroy** [comment]
I don't actually think rmcilroy/requestidlecallback@c216c4b fixes this (at least didn't seem to when I checked, that's why I hadn't made a pull request). Does it fix the issue when you checked?

**Comment by igrigorik** [comment]
cmd-shift-R... Doh.

@rmcilroy any objections to Marcos' suggestion on changing the example?

**Comment by rmcilroy** [comment]
Nope if that fixes it SGTM, thanks

**Comment by igrigorik** [comment]
Actually, it didn't.. Doh, again. @marcoscaceres back to the drawing board? :)

**Comment by marcoscaceres** [comment]
Could kindly try what I suggested here: 
https://github.com/w3c/requestidlecallback/issues/67#issuecomment-337467575

I hit a couple of snags replacing the markdown parse - other parsers are over 100kb minified (compared to ~40kb) for Marked.js... so I’m a bit hesitant to replace it as it would bloat ReSpec to over 500kb. I’ll investigate if there is a fix for this as a PR in marked.js’ repo. 

Alternatively, I’m also considering moving markdown parsing off main thread. It’s a bit more work, but might give the right balance between speed, download size, and not having this bug.

**Comment by igrigorik** [comment]
@marcoscaceres I did, same issue.

![image](https://user-images.githubusercontent.com/10652/32130312-2a952da0-bb4b-11e7-83cc-e6f5bae96f1e.png)

**Comment by marcoscaceres** [comment]
Apologies, I misread. I’ll try a few things out and get back to you soon!

**Comment by marcoscaceres** [comment]
Sent a PR for this: #69
