### ISSUE TITLE
Processing model will not make progress

### ISSUE THREAD

**Issue by lawnsea** [w3c/requestidlecallback#7]
The [Processing Model](https://w3c.github.io/requestidlecallback/#processing-model) says the following:

> 1. Let last_deadline be the last idle period deadline associated with the current event loop, or 0 if no previous deadline exists.
> 2. If last_deadline is less than the current time:
>    1. Wait until current time is equal to last_deadline.

The first time this is executed, there will be no last idle period deadline, so `last_deadline` will be 0. It will always be the case that `0 < performance.now()`, thus we take the branch at step 2 and wait for the current time to equal `last_deadline`, which will never happen.

**Comment by rmcilroy** [comment]
Yes you're right, thanks for the fix.
