### ISSUE TITLE
The timeRemaining language is confusing

### ISSUE THREAD

**Issue by szager-chromium** [w3c/requestidlecallback#77]
This section:

https://w3c.github.io/requestidlecallback/#the-idledeadline-interface

... says:

"When the timeRemaining() method is invoked on an IdleDeadline object it MUST return the duration, as a DOMHighResTimeStamp, between the current time and the time associated with the IdleDeadline object."

It then goes on to describe a different algorithm for computing the return value of timeRemaining. I think the above-quoted line is misleading and should be removed.

**Comment by yoavweiss** [comment]
Closed by #79
