### ISSUE TITLE
Starting of an idle period algorithm should take origin into account

### ISSUE THREAD

**Issue by rniwa** [w3c/requestidlecallback#81]
The [event loop processing model](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model) states to [start an idle period algorithm](https://w3c.github.io/requestidlecallback/#start-an-idle-period-algorithm) when there is no task in the event loop's task queues and event loop's micro task queue is empty.

This exposes tasks and micro tasks enqueued in cross origin documents. This is not okay.

@annevk @smaug----

**Comment by rniwa** [comment]
I guess "none of the browsing contexts have a rendering opportunity" is also not right. It exposes whether any of the cross-origin documents have done something to cause a rendering opportunity to occur.

**Comment by annevk** [comment]
Are you concerned with cross-origin-but-same-site documents or cross-site documents that ought to run in their own agent cluster likely with their own event loop?

cc @domenic

**Comment by rniwa** [comment]
Oh, right. I had forgotten about the agent clustering refactoring you had been doing. So event loops are separate between cross-site documents so this should be fine in terms of post Spectre security model.

**Comment by annevk** [comment]
Theoretically, though there's probably edge cases and a bunch of wording to be improved.
