### ISSUE TITLE
6.2. invoke idle callbacks algorithm step 1 should be defined in terms of task sources having tasks enqueued

### ISSUE THREAD

**Issue by rniwa** [w3c/requestidlecallback#86]
https://w3c.github.io/requestidlecallback/#invoke-idle-callbacks-algorithm says
> If the user-agent believes it should end the idle period early due to newly scheduled high-priority work, skip to step 4.

This should be defined in terms of any of the task sources in the HTML5 event loop having a  task enqueued.

**Comment by noamr** [comment]
I think this is solved by https://github.com/w3c/requestidlecallback/pull/95 and https://github.com/whatwg/html/pull/7166 once they are merged.

**Comment by noamr** [comment]
I believe this can be closed now that https://github.com/w3c/requestidlecallback/pull/95 is merged.

**Comment by yoavweiss** [comment]
@rniwa - Any objections to closing this?

**Comment by noamr** [comment]
Closing. Feel free to reopen.
