### ISSUE TITLE
timeRemaining() step 4 should define what it means to have a "time-critical task pending"

### ISSUE THREAD

**Issue by rniwa** [w3c/requestidlecallback#87]
https://w3c.github.io/requestidlecallback/#dom-idledeadline-timeremaining says:
> If the user agent now has a time-critical task pending, set timeRemaining to 0.

Like https://github.com/w3c/requestidlecallback/issues/86, this needs to be defined in terms of event loop's task sources having a task enqueued.

**Comment by noamr** [comment]
I think this is solved by https://github.com/w3c/requestidlecallback/pull/95 and https://github.com/whatwg/html/pull/7166 once they are merged.

**Comment by noamr** [comment]
I believe this can be closed now that https://github.com/w3c/requestidlecallback/pull/95 is merged.

**Comment by yoavweiss** [comment]
@rniwa - Any objections to closing this?

**Comment by noamr** [comment]
Closing. Feel free to reopen.
